sudo: required

services:
  - docker

env:
  matrix:
    - DOCKER_TAG=perl-5.10
    - DOCKER_TAG=perl-5.18

script:
  - docker build -t mt-test -f Dockerfile.$DOCKER_TAG --cache-from masiuchi/docker-mt-test:$DOCKER_TAG .

