sudo: required

services:
  - $HOME/docker

cache:
  directories:
    - .docker

before_script:
  - if [ -e $HOME/docker/image.tar ]; then docker load -i $HOME/docker/image.tar; fi

script:
  - docker build -t mt-test .

before_cache:
  - docker save mt-test > $HOME/docker/image.tar

