version: '3'

services:
  mt-test:
    build: .
    volumes:
      - ./:/root
    working_dir: /root/movabletype
    command: bash -c "bash ../preprocess.sh && prove -j4 -PMySQLPool=MT::Test::Env -It/lib t plugins/*/t && phpunit"

